server:
  port: 8088

spring:
  redis:
    port: 6379
    host: 127.0.0.1
  thymeleaf:
    cache: false
    prefix: /
    suffix: .html
wx:
  createTicketUrl: https://api.weixin.qq.com/cgi-bin/qrcode/create
  showQrcodeUrl: https://mp.weixin.qq.com/cgi-bin/showqrcode?ticket=%s
  shortQrcodeUrl: https://api.weixin.qq.com/cgi-bin/shorturl
  appId: ******************
  appsecret: **************



